7. What is the customer count and percentage breakdown of all 5 plan_name values at 2020-12-31?

WITH CTE AS( 
SELECT * 
,ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY START_DATE DESC)  AS ROW_NUMBER 
FROM SUBSCRIPTIONS 
WHERE START_DATE <= '2020-12-31'
)
SELECT COUNT(CUSTOMER_ID) AS CUSTOMER_COUNT
,PLAN_NAME
,(SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SUBSCRIPTIONS) AS TOTAL_CUSTOMERS
,ROUND(COUNT(CUSTOMER_ID) / (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SUBSCRIPTIONS)*100,1) AS PERCENTAGE
FROM CTE
INNER JOIN PLANS AS P 
ON CTE.PLAN_ID = P.PLAN_ID
WHERE ROW_NUMBER = 1
GROUP BY PLAN_NAME
