9.How many days on average does it take for a customer to an annual plan from the day they join Foodie-Fi?

WITH TRIAL_TABLE AS(
SELECT CUSTOMER_ID
,START_DATE AS TRIAL_START_DATE
FROM SUBSCRIPTIONS
WHERE PLAN_ID = 0
)

,ANNUAL_TABLE AS(
SELECT CUSTOMER_ID
,START_DATE AS ANNUAL_START_DATE
FROM SUBSCRIPTIONS AS S
WHERE PLAN_ID = 3
)
SELECT 
ROUND(AVG(DATEDIFF('day',TRIAL_START_DATE,ANNUAL_START_DATE)),2) AS AVG_DAYS_DIFF
FROM TRIAL_TABLE AS T
INNER JOIN ANNUAL_TABLE AS A
ON T.CUSTOMER_ID = A.CUSTOMER_ID
