//How many customers have churned straight after their initial free trial - what percentage is this rounded to the nearest whole number?

WITH CTE AS (
SELECT CUSTOMER_ID
,PLAN_NAME
,ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY START_DATE) AS ROW_NUMBER
FROM SUBSCRIPTIONS AS S 
INNER JOIN PLANS AS P 
ON S.PLAN_ID = P.PLAN_ID
)
SELECT 
COUNT (DISTINCT CUSTOMER_ID) AS CHURNED_STRAIGHT_AWAY
,ROUND( 
COUNT (DISTINCT CUSTOMER_ID) / (SELECT COUNT (DISTINCT CUSTOMER_ID) FROM SUBSCRIPTIONS)*100
,0)
AS IMMEDIATE_CHURN_RATE
FROM CTE
WHERE ROW_NUMBER = 2
AND PLAN_NAME = 'churn'
