//What is the customer count and percentage of customers who have churned rounded to 1 decimal place?

SELECT 
(SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SUBSCRIPTIONS) AS CUSTOMER_COUNT
, ROUND(
COUNT (DISTINCT CUSTOMER_ID) 
/
(SELECT COUNT (DISTINCT CUSTOMER_ID) FROM SUBSCRIPTIONS)*100
,1)
AS CHURN_RATE
FROM SUBSCRIPTIONS 
WHERE PLAN_ID = 4

